on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v1.4
        id: deployment
        with:
          step: start
          env: develop

      - name: dummy deploy
        run: echo "ref ${{ github.ref }}"

      - name: update deployment
        uses: bobheadxi/deployments@v1.4
        with:
          step: finish
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
